export const ndata = [
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2023/02/TikTok-News-Header-1.png",
    text: "Now Available! RentSocial. for TikTok connects properties with renter audiences",
    tag: "News",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2023/01/Copy-of-square-property-sites-image.jpg",
    text: "BusinessWire: Rent. announces Property Sites, a website solution for the multifamily industry.",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2023/01/Untitled-design-1000x667-1.jpg",
    text: "Data Shapes The Future Of Your Property’s Marketing Plan",
    tag: "News",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/onlineengagement.jpg",
    text: "NAA Units Magazine: Proven Ways to Resonate with Today’s Renters Online",
    tag: "News",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/webinar-images-300-%C3%97-250-px.jpg",
    text: "The Multifamily Innovation® Show: Nishant Phadnis featured in Meet the Sponsors Series",
    tag: "News",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/3.jpg",
    text: "New alliance delivers the best of rental reputation management all in one platform",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/11/wordpress-image-marketing-dive-2022.jpg",
    text: "Marketing Dive: Rent. creates TikTok solutions platform",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/11/OPTECH-Product-Announcement-Blog-Header.png",
    text: "Industry’s first data-driven TikTok solution and turn-key website builder unveiled at OPTECH 2022",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),

    img: "https://solutions.rent.com/wp-content/uploads/2022/10/US-News-World-Report-Blog-header.jpg",
    text: "Should You Hire a Property Manager?",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/10/2022-NMHC-OpTech-News-Header-2.jpg",
    text: "Build a better future for your property with Rent. at OPTECH 2022",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/RentMarketplace-Sept-2022-updates.jpg",
    text: "RentMarketplace. goes local, boosts performance, and now syncs to Google",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/4.jpg",
    text: "CCR Magazine: Navigating a company rebrand can be a challenge",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/1662129734-GettyImages-1176854253.jpg",
    text: "Entrepreneur: Property tech is creating an incredible real estate opportunity for entrepreneurs",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),

    img: "https://solutions.rent.com/wp-content/uploads/2022/09/169kathheds493342-1170x600-1.jpg",
    text: "Anatomy of a Rebrand – a Q&A with Kathy Neumann, CMO of Rent.",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/08/WIL-Panel-2022-BLOG-header.jpg",
    text: "Rent. celebrates Women’s Equality Day 2022",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/motley-fool-image-2.jpg",
    text: "The Motley Fool: What’s going on in the housing market?",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/meet-the-sponsors-rent-1168x657-1.jpg",
    text: "Multifamily Women® Podcast: Interview with Rent. CMO Kathy Neumann",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/08/Screen-Shot-2022-08-04-at-9.46.38-AM.jpg",
    text: "CBS News: Apartment rents are shooting up in hundreds of cities across the U.S. Here’s why.",
    tag: "News",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/07/JZ-interview-Goals-2022-.jpg",
    text: "The Motley Fool: CEO Jon Ziglar talks rental trends and the future of Rent.",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/07/digitalcurbappeal.jpeg",
    text: "NAA: 4 ways to improve digital curb appeal",
    tag: "News",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/07/Rent-Announcement-News-Header.jpg",
    text: "Business Wire: RentPath becomes Rent. and simplifies the rentals marketplace",
    tag: "News",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/07/GettyImages-1127957300.jpg",
    text: "Why renters move: affordability and how your property can compete",
    tag: "News",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2023/01/Untitled-design-1000x667-1.jpg",
    text: "Data Shapes The Future Of Your Property’s Marketing Plan",
    tag: "News",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/onlineengagement.jpg",
    text: "NAA Units Magazine: Proven Ways to Resonate with Today’s Renters Online",
    tag: "News",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/webinar-images-300-%C3%97-250-px.jpg",
    text: "The Multifamily Innovation® Show: Nishant Phadnis featured in Meet the Sponsors Series",
    tag: "News",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/3.jpg",
    text: "New alliance delivers the best of rental reputation management all in one platform",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/11/wordpress-image-marketing-dive-2022.jpg",
    text: "Marketing Dive: Rent. creates TikTok solutions platform",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/11/OPTECH-Product-Announcement-Blog-Header.png",
    text: "Industry’s first data-driven TikTok solution and turn-key website builder unveiled at OPTECH 2022",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/10/US-News-World-Report-Blog-header.jpg",
    text: "Should You Hire a Property Manager?",
    tag: "Press",
  },
  {
    id: Math.floor(Math.random() * 1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/10/2022-NMHC-OpTech-News-Header-2.jpg",
    text: "Build a better future for your property with Rent. at OPTECH 2022",
    tag: "Press",
  },

  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2023/01/Untitled-design-1000x667-1.jpg",
    text: "Data Shapes The Future Of Your Property’s Marketing Plan",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/onlineengagement.jpg",
    text: "NAA Units Magazine: Proven Ways to Resonate with Today’s Renters Online",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2023/02/TikTok-News-Header-1.png",
    text: "Now Available! RentSocial. for TikTok connects properties with renter audiences",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/webinar-images-300-%C3%97-250-px.jpg",
    text: "The Multifamily Innovation® Show: Nishant Phadnis featured in Meet the Sponsors Series",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/08/Screen-Shot-2022-08-04-at-9.46.38-AM.jpg",
    text: "CBS News: Apartment rents are shooting up in hundreds of cities across the U.S. Here’s why.",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/07/digitalcurbappeal.jpeg",
    text: "NAA: 4 ways to improve digital curb appeal",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/07/Rent-Announcement-News-Header.jpg",
    text: "Business Wire: RentPath becomes Rent. and simplifies the rentals marketplace",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/07/GettyImages-1127957300.jpg",
    text: "Why renters move: affordability and how your property can compete",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/onlineengagement.jpg",
    text: "NAA Units Magazine: Proven Ways to Resonate with Today’s Renters Online",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2023/02/TikTok-News-Header-1.png",
    text: "Now Available! RentSocial. for TikTok connects properties with renter audiences",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/webinar-images-300-%C3%97-250-px.jpg",
    text: "The Multifamily Innovation® Show: Nishant Phadnis featured in Meet the Sponsors Series",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/08/Screen-Shot-2022-08-04-at-9.46.38-AM.jpg",
    text: "CBS News: Apartment rents are shooting up in hundreds of cities across the U.S. Here’s why.",
    tag: "News",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/07/digitalcurbappeal.jpeg",
    text: "NAA: 4 ways to improve digital curb appeal",
    tag: "News",
  },

  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2023/01/Copy-of-square-property-sites-image.jpg",
    text: "BusinessWire: Rent. announces Property Sites, a website solution for the multifamily industry.",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/3.jpg",
    text: "New alliance delivers the best of rental reputation management all in one platform",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/11/wordpress-image-marketing-dive-2022.jpg",
    text: "Marketing Dive: Rent. creates TikTok solutions platform",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/11/OPTECH-Product-Announcement-Blog-Header.png",
    text: "Industry’s first data-driven TikTok solution and turn-key website builder unveiled at OPTECH 2022",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/10/US-News-World-Report-Blog-header.jpg",
    text: "Should You Hire a Property Manager?",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/10/2022-NMHC-OpTech-News-Header-2.jpg",
    text: "Build a better future for your property with Rent. at OPTECH 2022",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/RentMarketplace-Sept-2022-updates.jpg",
    text: "RentMarketplace. goes local, boosts performance, and now syncs to Google",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/4.jpg",
    text: "CCR Magazine: Navigating a company rebrand can be a challenge",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/1662129734-GettyImages-1176854253.jpg",
    text: "Entrepreneur: Property tech is creating an incredible real estate opportunity for entrepreneurs",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/169kathheds493342-1170x600-1.jpg",
    text: "Anatomy of a Rebrand – a Q&A with Kathy Neumann, CMO of Rent.",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/08/WIL-Panel-2022-BLOG-header.jpg",
    text: "Rent. celebrates Women’s Equality Day 2022",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/motley-fool-image-2.jpg",
    text: "The Motley Fool: What’s going on in the housing market?",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/meet-the-sponsors-rent-1168x657-1.jpg",
    text: "Multifamily Women® Podcast: Interview with Rent. CMO Kathy Neumann",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/07/JZ-interview-Goals-2022-.jpg",
    text: "The Motley Fool: CEO Jon Ziglar talks rental trends and the future of Rent.",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/12/3.jpg",
    text: "New alliance delivers the best of rental reputation management all in one platform",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/11/wordpress-image-marketing-dive-2022.jpg",
    text: "Marketing Dive: Rent. creates TikTok solutions platform",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/11/OPTECH-Product-Announcement-Blog-Header.png",
    text: "Industry’s first data-driven TikTok solution and turn-key website builder unveiled at OPTECH 2022",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/10/US-News-World-Report-Blog-header.jpg",
    text: "Should You Hire a Property Manager?",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/10/2022-NMHC-OpTech-News-Header-2.jpg",
    text: "Build a better future for your property with Rent. at OPTECH 2022",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/RentMarketplace-Sept-2022-updates.jpg",
    text: "RentMarketplace. goes local, boosts performance, and now syncs to Google",
    tag: "Press",
  },
  {id:Math.floor(Math.random()*1000),
    img: "https://solutions.rent.com/wp-content/uploads/2022/09/4.jpg",
    text: "CCR Magazine: Navigating a company rebrand can be a challenge",
    tag: "Press",
  },
];

export default ndata;
